// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.service;

import com.stripe.exception.StripeException;
import com.stripe.model.BitcoinTransactionCollection;
import com.stripe.net.ApiService;
import com.stripe.net.RequestOptions;
import com.stripe.param.BitcoinTransactionListParams;

/**
 * Service class for {@link com.stripe.model.BitcoinTransaction}, and is now a preferred way to
 * making API requests.The original methods in model class will be marked deprecated in the next
 * major version.
 */
public class BitcoinTransactionService extends ApiService {
  /** List bitcoin transacitons for a given receiver. */
  public BitcoinTransactionCollection list(String receiver, BitcoinTransactionListParams params)
      throws StripeException {
    return list(receiver, params, (RequestOptions) null);
  }

  /** List bitcoin transacitons for a given receiver. */
  public BitcoinTransactionCollection list(
      String receiver, BitcoinTransactionListParams params, RequestOptions options)
      throws StripeException {
    String url = resourceUrl("/v1/bitcoin/receivers/%s/transactions", receiver);
    return requestCollection(url, params, BitcoinTransactionCollection.class, options);
  }
}
