// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.service;

import com.stripe.exception.StripeException;
import com.stripe.model.LoginLink;
import com.stripe.net.ApiResource;
import com.stripe.net.ApiService;
import com.stripe.net.RequestOptions;
import com.stripe.param.LoginLinkCreateParams;

/**
 * Service class for {@link LoginLink}, and is now a preferred way to making API requests.The
 * original methods in model class will be marked deprecated in the next major version.
 */
public class LoginLinkService extends ApiService {
  /**
   * Creates a single-use login link for an Express account to access their Stripe dashboard.
   *
   * <p><strong>You may only create login links for <a href="/docs/connect/express-accounts">Express
   * accounts</a> connected to your platform</strong>.
   */
  public LoginLink create(String account, LoginLinkCreateParams params) throws StripeException {
    return create(account, params, (RequestOptions) null);
  }

  /**
   * Creates a single-use login link for an Express account to access their Stripe dashboard.
   *
   * <p><strong>You may only create login links for <a href="/docs/connect/express-accounts">Express
   * accounts</a> connected to your platform</strong>.
   */
  public LoginLink create(String account, LoginLinkCreateParams params, RequestOptions options)
      throws StripeException {
    String url = resourceUrl("/v1/accounts/%s/login_links", account);
    return request(ApiResource.RequestMethod.POST, url, params, LoginLink.class, options);
  }
}
